name: Build

on: push


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [Shipping]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Update Stuff
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libnotify-dev
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Workspace -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DGODOT=1 -DGODOT_GDEXTENSION_DIR="gdextension" -DGODOT_CPP_SYSTEM_HEADERS=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: Build
      run: cmake --build ${{github.workspace}}/Workspace --config ${{matrix.BUILD_TYPE}}
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TYPE: [ Shipping ]
    steps:
      - uses: actions/checkout@v3
      - name: Update Stuff
        run: |
          vcpkg install curl
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/Workspace -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DGODOT=1 -DGODOT_GDEXTENSION_DIR="gdextension" -DGODOT_CPP_SYSTEM_HEADERS=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 17 2022"
      - name: Build
        run: cmake --build ${{github.workspace}}/Workspace
